#!/usr/bin/env bash
# docstring=transcript of youtube videos
set -E -o pipefail
shopt -s failglob
export LC_ALL=C.UTF8

TEMP_FOLDER='/tmp/dlp-trnsrpt'
mkdir -p "$TEMP_FOLDER"
cd "$TEMP_FOLDER" || exit 1

yt-dlp --write-auto-sub --sub-langs 'en.*,.*orig' --convert-subs=srt --skip-download "$*"
nvim "$TEMP_FOLDER"/*-orig*
