#!/usr/bin/env bash
# docstring=do a screenshots on wayland compositors
set -E -o pipefail
shopt -s failglob
export LC_ALL=C.UTF8

grim -g "$(slurp -o -r -c '#ff0000ff')" - | satty --filename - --fullscreen --output-filename ~/Media/Pictures/Screenshots/satty-$(date '+%Y%m%d-%H:%M:%S').png
