#!/usr/bin/env bash
# docstring=do a screenshots on wayland compositors
set -E -o pipefail
shopt -s failglob
export LC_ALL=C.UTF8

PICTURES="$HOME"

source "/etc/xdg/user-dirs.defaults"
source "$XDG_CONFIG_HOME/user-dirs.dirs"

mkdir -p "$PICTURES"

grim -g "$(slurp -o -r -c '#ff0000ff')" - \
  | satty \
      --filename - \
      --fullscreen \
      --initial-tool "crop" \
      --output-filename "$PICTURES/Screenshots/satty-$(date '+%Y%m%d-%H:%M:%S').png"
