#!/usr/bin/env bash
# docstring=do a screenshots on wayland compositors
# dependencies=grim, slurp, satty

set -E -o pipefail
shopt -s failglob
export LC_ALL=C.UTF8

PICTURES="$HOME"

source "/etc/xdg/user-dirs.defaults"
source "$XDG_CONFIG_HOME/user-dirs.dirs"

mkdir -p "$PICTURES"

dimensions="$(slurp -o -r -c '#ff0000ff')"

sleep "${1:-0}"

grim -g "$dimensions" - \
  | satty \
      --filename - \
      --fullscreen \
      --initial-tool "crop" \
      --annotation-size-factor "0.75" \
      --output-filename "$PICTURES/Screenshots/satty-$(date '+%Y%m%d-%H:%M:%S').png"
