#!/usr/bin/env python3
# docstring=wraps kanshictl and adds features
import os
import os.path as path

HOME = os.environ["HOME"]
CFG = {
    "config_path": path.join(HOME, ".config/kanshi/config")
}

def extract_layouts(config_path=CFG["config_path"]):
    with open(config_path, "r") as file_fd:
        for line in file_fd:
            print(line)


def main():
    extract_layouts()


if __name__ == "__main__":
    main()
