#!/usr/bin/env python

from os import path
from pathlib import PosixPath
import os
import subprocess as sp
import sys


def main():
    user_run = os.getenv("XDG_RUNTIME_DIR")
    if not user_run:
        user_run = PosixPath(path.join(os.environ["HOME"], ".local/mnt"))
    else:
        user_run = PosixPath(user_run)
    user_run = user_run.joinpath("sfs", sys.argv[1])
    user_run.mkdir(parents=True, exist_ok=True)

    cmd = ["sshfs", sys.argv[1] + ":/", user_run]

    print(cmd)
    sp.run(cmd)

if __name__ == "__main__":
    main()


